doctrine:
    dbal:
        default_connection: gite
        connections:
            gite:
                driver: '%env(resolve:pdo_mysql)%'
                host: '%env(resolve:DB_HOST)%'
                port: '%env(resolve:DB_PORT)%'
                dbname: '%env(resolve:DB_DATABASE)%'
                user: '%env(resolve:DB_USERNAME)%'
                password: '%env(resolve:DB_PASSWORD)%'
                charset: UTF8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
